[project]
name = "thelepath"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chromadb>=1.5.6",
    "fastembed>=0.8.0",
    "langchain-text-splitters>=1.1.1",
    "qdrant-client>=1.17.1",
    "requests>=2.33.1",
    "sentence-transformers>=5.3.0",
]

[dependency-groups]
dev = [
    "mypy>=1.20.1",
    "ruff>=0.15.11",
]

[tool.ruff]
line-length = 79
target-version = "py312"

[tool.ruff.lint]
# D (Docstrings), ANN (Annotations), PT (Pytest), SIM (Simplify), ARG (Unused arguments)
select = ["E", "F", "I", "N", "UP", "D", "ANN", "SIM", "ARG"]
ignore = [
    "D100", # Missing docstring in public module
    "D104", # Missing docstring in public package
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.mypy]
python_version = "3.12"
strict = true
ignore_missing_imports = true
exclude = ["venv", ".venv"]
explicit_package_bases = true
mypy_path = "."
# Maximum strictness settings
disallow_untyped_defs = true
disallow_any_generics = true
check_untyped_defs = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true
show_error_codes = true
